---
- name: Get API access token using a temporary offline token
  uri:
    url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
    method: POST
    return_content: True
    body_format: form-urlencoded
    headers:
      accept: application/json
    body:
      grant_type: refresh_token
      client_id: rhsm-api
      refresh_token: '{{ my_offline_token }}'
    validate_certs: False
  register: access_token_response

- name: Print API access token
  set_fact:
    token: '{{ access_token_response.json.access_token }}'

- name: Output token
  debug:
    var: token

